CREATE TABLE D500L
(
  GSDM            NVARCHAR2(4),
  BDDM            NVARCHAR2(4),
  BDBH            NVARCHAR2(20),
  PROJECT         VARCHAR2(10 BYTE),
  ITEM            VARCHAR2(5 BYTE),
  FUN_DESCRIPT    VARCHAR2(50 BYTE),
  LOCATION        VARCHAR2(10 BYTE),
  ERROR_DESCRIPT  VARCHAR2(200 BYTE),
  PROD_NO_OLD     VARCHAR2(200 BYTE),
  PROD_NO_NEW     VARCHAR2(200 BYTE),
  BUILDER_DATE    DATE,
  BUILDER         VARCHAR2(20 BYTE)
)