CREATE TABLE D500H
(
  GSDM           NVARCHAR2(4),
  BDDM           NVARCHAR2(4),
  BDBH           NVARCHAR2(20),
  BDRQ           NVARCHAR2(8),
  QHYH           NVARCHAR2(30),
  QHSJ           DATE,
  JLYH           NVARCHAR2(30),
  JLSJ           DATE,
  GXYH           NVARCHAR2(30),
  GXSJ           DATE,
  SQYH           VARCHAR2(40 BYTE),
  BDZT           VARCHAR2(1 BYTE),
  BDJG           VARCHAR2(1 BYTE),
  PROD_NO_NEW    VARCHAR2(20 BYTE)              NOT NULL,
  PROD_NO_OLD    VARCHAR2(20 BYTE),
  STATUS         VARCHAR2(20 BYTE),
  EE      VARCHAR2(20 BYTE),
  EE_DATE  DATE,
  ME      VARCHAR2(20 BYTE),
  ME_DATE  DATE,
  EE_LEADER      VARCHAR2(20 BYTE),
  EE_CHECK_DATE  DATE,
  ME_LEADER      VARCHAR2(20 BYTE),
  ME_CHECK_DATE  DATE,
  CONTENT        VARCHAR2(1000 BYTE)
)


ALTER TABLE D500H 
ADD CONTENT VARCHAR2(1000 BYTE) DEFAULT '';