
CREATE TABLE D888H
(
  GSDM   NVARCHAR2(4),
  BDDM   NVARCHAR2(4),
  BDBH   NVARCHAR2(20),
  BDRQ   NVARCHAR2(8),
  CCLX   NVARCHAR2(20),--出厂类型
  BMMC   NVARCHAR2(40),--部门名称
  BMBH   NVARCHAR2(30),--部门编号
  CCBH   NVARCHAR2(50),--财产编号
  LLBH   NVARCHAR2(50),--领料编号
  TLBH   NVARCHAR2(50),--退料编号
  WLBH   NVARCHAR2(50),--物料编号
  DDBH   NVARCHAR2(50),--订单编号
  ZJE   NUMBER(18,2),--总金额
  GYSM  NVARCHAR2(100), --供應商名
  BDGZ  NVARCHAR2(20),--表單跟蹤
  BDFD   NVARCHAR2(200),--附档
  QHYH   NVARCHAR2(30),
  QHSJ   DATE,
  JLYH   NVARCHAR2(30),
  JLSJ   DATE,
  GXYH   NVARCHAR2(30),
  GXSJ   DATE,
  SQYH   VARCHAR2(40 BYTE),
  BDZT   VARCHAR2(1 BYTE),
  BDJG   VARCHAR2(1 BYTE),
  CCNR  CLOB,
  WJJM   NVARCHAR2(30),
  DYZT   CHAR(1 BYTE)
)